// <auto-generated />
namespace MoSocioAPI.DAC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial_migration_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_migration_create));
        
        string IMigrationMetadata.Id
        {
            get { return "202112302122094_initial_migration_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
