// <auto-generated />
namespace MoSocioAPI.DAC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class refinamento_das_entidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refinamento_das_entidades));
        
        string IMigrationMetadata.Id
        {
            get { return "202201061720322_refinamento_das_entidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
