// <auto-generated />
namespace MoSocioAPI.DAC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_contactInstitution_and_addressInstitution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_contactInstitution_and_addressInstitution));
        
        string IMigrationMetadata.Id
        {
            get { return "202201021051139_create_contactInstitution_and_addressInstitution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
