// <auto-generated />
namespace MoSocioAPI.DAC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class refactoracao_do_modelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoracao_do_modelo));
        
        string IMigrationMetadata.Id
        {
            get { return "202201301939286_refactoracao_do_modelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
